### ISSUE TITLE
Deployment with CMake

### ISSUE THREAD

**Issue by kreuzberger** [ThoSe1990/cwt-cucumber#18]
Hi!
I was trying to use the project in my source code (mainly by creating a conanfile.py).
I saw that there is a different repo which also tries to to do that.

Cause you are using cmake, i think it could be more "generic" to use CMake functions to deploy and generate an "importable" package. See https://cmake.org/cmake/help/v3.28/guide/importing-exporting/index.html#exporting-targets.
So the package could be used also with conan and cmake External.... Methods in the same way and the proper deployment (libs and headers) its up to the cwt-cucumber project. 

Any doubts/concerns about that idea?

**Comment by ThoSe1990** [comment]
Hi there, 

I honestly never used cmake's exporting targets. So if this works out for you and you're able to use it, I don't see any problem here. 

Most of my projects use conan and in order to use cwt-cucumber as conan package I just create the package locally. I think this u meant with a different repo? (I didn't push it to the conan center or any other package center yet)

**Comment by ThoSe1990** [comment]
Thanks a lot, I just merged the branch and close this issue
