### ISSUE TITLE
Automatic function name generation

### ISSUE THREAD

**Issue by kreuzberger** [ThoSe1990/cwt-cucumber#21]
In the steps definitions whe have to define "function_names" which are more or less "irrelevant" for the user/implementor.
Could those functions names not be autogenerated e.g. by using CONCAT(__SHORT_FILE__, __LINE__)
This would make hook generation "simpler"

Another alternative could be to use  \_\_COUNTER\_\_  variable if available, else the other solution could be used

**Comment by ThoSe1990** [comment]
The problem with this is that `__COUNTER__` is per compilation unit. Which means if you spread the step definitions into multiple files, function names can collide. Using multiple files for step definitions ruled the `__COUNTER___` out for me

**Comment by kreuzberger** [comment]
In this case the solution with short_file and line should always work. This is what other gherkin / cucumber parser also do?

**Comment by ThoSe1990** [comment]
I just noted. that this is still unanswered here. 

I don't exactly know what `SHORT_FILE` is (?).

The problem in general is that the defines GIVEN, WHEN, etc. use the preprocessor to create the function name and the defined signature. The problem with the given compiler defines like `__FILE__` is that `/` is invalid C++ syntax. This means we have to manipulate the string, but the preprocessor can not do this (at least i did not find a way to do so). 

When adding a unique identifier to `GIVEN`, `WHEN`, etc. we can create a unique function name. Essentially I use a similar technique like GTest to create the callbacks. I did some research again and I did not find a way to reliably create a unique name based on the file path with the preprocessor. 

I don't know how deep you dived into the macros, I can break down the problem with examples if you're interested

**Comment by kreuzberger** [comment]
I thougt _SHORT_FILE_ would be a generic macro from the compiler, but it was a macro from our company code. So do not care about :smile:. I am currently glad with the solution, cause i  need the identifier to reference the steps in my documentation generated out of the steps catalog. So this is just fine and does not need further discussions for me.

For your solution: maybe this could be an valid approach to get hash values at compile time.
https://github.com/Cyan4973/xxHash/issues/496
But i am not so deep in C++ Details to give you more hints :smile:

**Comment by ThoSe1990** [comment]
No `SHORT_FILE` is perhaps your internal macro. 

Even with the idea of some compile time programming this does not really work, because at this step the string of our filename should already be in valid syntax. This isn't the case with `/` and `.` in the path. 

WIth using the preprocessor this works because it essentially does copy/paste here to insert the function name. In some IDEs you can hover over the define and see to what the macro expands. This means in the compilation process the preprocessing step should modify the given string and replace or remove invalid characters. But this is not possible (as far as i'm concerned). 

This means that we don't get that far to even use compile time programming because we don't have a valid compilation unit. 

If there is a solid way to solve this I'm really open to do so, right now I don't see a way doing so.
